"""Helix vault — operator-facing markdown export of the knowledge store.

VaultManager is the public API. It owns:
- VaultState (vault.db)
- VaultLock (file lock)
- A pruner thread (TTL prune + _stale/ refresh)

The writer functions are stateless — VaultManager holds the dependencies
and dispatches to them.
"""
from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Optional

from cymatix_context.telemetry import vault_file_count_gauge
from cymatix_context.vault import pruner as pruner_mod
from cymatix_context.vault import writer as writer_mod
from cymatix_context.vault.locking import VaultLock
from cymatix_context.vault.state import VaultState

log = logging.getLogger(__name__)


class VaultManager:
    """Top-level vault lifecycle. Wired into the FastAPI lifespan.

    Per Invariant I-1, vault failures never degrade retrieval. Every public
    method on VaultManager catches its exceptions internally and logs them.
    """

    def __init__(self, *, config, genome) -> None:
        self.config = config
        self.genome = genome
        self.vault_root: Optional[Path] = None
        self.state: Optional[VaultState] = None
        self.lock: Optional[VaultLock] = None
        self._pruner_thread: Optional[threading.Thread] = None
        self._stop_event = threading.Event()
        self._started = False

    # ── Lifecycle ──────────────────────────────────────────────────────

    def start(self) -> None:
        if not self.config.vault.enabled:
            log.info("vault disabled (config.vault.enabled=false)")
            return
        try:
            self.vault_root = Path(self.config.vault.path).expanduser()
            self.vault_root.mkdir(parents=True, exist_ok=True, mode=0o700)
            self._cleanup_stale_sentinel()
            self.state = VaultState(vault_root=self.vault_root)
            self.lock = VaultLock(vault_root=self.vault_root)
            self._write_readme()
            self._start_pruner_thread()
            self._started = True
            log.info("vault started at %s", self.vault_root)
        except OSError:
            log.warning("vault start failed; vault disabled", exc_info=True)
            self._started = False

    def stop(self) -> None:
        if not self._started:
            return
        self._stop_event.set()
        if self._pruner_thread is not None:
            self._pruner_thread.join(timeout=5)
        if self.state is not None:
            self.state.close()
        self._started = False

    def _cleanup_stale_sentinel(self) -> None:
        sentinel = self.vault_root / ".helix-syncing"
        try:
            sentinel.unlink()
            log.info("cleaned stale .helix-syncing sentinel")
        except FileNotFoundError:
            pass
        except OSError:
            log.warning("could not clean stale sentinel", exc_info=True)

    def _write_readme(self) -> None:
        readme = self.vault_root / "README.md"
        if readme.exists():
            return  # don't clobber operator-edited READMEs
        content = (
            "# Helix vault\n\n"
            "Generated by helix-context. Do NOT edit gene frontmatter or body in v1 "
            "— edits are not synced back. Authored fields render as cosmetic "
            "placeholders for forward-compat with v1.1.\n\n"
            "## Layout\n\n"
            "- `genes/<domain>/<stem>-<id>.md` — exported genes (one per gene_id)\n"
            "- `_traces/` — diagnostic exports of recent /context calls (auto-pruned)\n"
            "- `_traces-pinned/` — operator-preserved traces; immune to TTL prune\n"
            "  (subject to `vault.traces.max_retention_hours_hard`)\n"
            "- `_stale/` — read-only view of genes with low live_truth_score\n"
            "- `_meta/` — rollups and aggregations\n"
            "- `_sessions/` — per-participant activity logs\n\n"
            "## Backup\n\n"
            "The genome can re-render every gene file from `genome.db` alone. "
            "However, pinned traces (`_traces-pinned/`) exist only here. If you "
            "depend on them, back up the **whole vault folder** alongside `genome.db`.\n\n"
            "## v1.1 follow-up\n\n"
            "Authored fields (operator_notes, operator_tags, pinned, supersedes...) "
            "are placeholders in v1. v1.1 enables write-back via watcher + validator. "
            "See `docs/ops/OBSIDIAN_VAULT_STATUS.md` for current operator status and "
            "the v1.1+ deferred work.\n"
        )
        readme.write_text(content, encoding="utf-8")

    def _start_pruner_thread(self) -> None:
        def _loop():
            interval = max(60, self.config.vault.traces.prune_interval_minutes * 60)
            while not self._stop_event.wait(interval):
                try:
                    self.run_prune_cycle()
                except Exception:
                    # Pruner thread must NEVER die — catch broad here
                    log.warning("prune cycle failed", exc_info=True)

        self._pruner_thread = threading.Thread(
            target=_loop, name="helix-vault-pruner", daemon=True
        )
        self._pruner_thread.start()

    # ── Public methods ─────────────────────────────────────────────────

    def full_export(self) -> dict:
        if not self._started:
            return {"genes_exported": 0, "elapsed_seconds": 0, "errors": 0, "skipped": "vault disabled"}
        return writer_mod.full_export(
            genome=self.genome,
            state=self.state,
            lock=self.lock,
            vault_root=self.vault_root,
            party_id=self.config.vault.party_id,
            redact_body=self.config.vault.redact_body,
            fan_out_threshold=self.config.vault.fan_out_threshold,
        )

    def incremental_export(self, since_ts: Optional[float] = None) -> dict:
        if not self._started:
            return {"genes_exported": 0, "elapsed_seconds": 0, "errors": 0}
        if since_ts is None:
            top = self.state.read_top_level_state()
            since_ts = max(top["last_full_export_ts"], top["last_incremental_export_ts"])
        return writer_mod.incremental_export(
            genome=self.genome,
            state=self.state,
            lock=self.lock,
            vault_root=self.vault_root,
            party_id=self.config.vault.party_id,
            redact_body=self.config.vault.redact_body,
            fan_out_threshold=self.config.vault.fan_out_threshold,
            since_ts=since_ts,
        )

    def trace_export(self, **kwargs) -> Path:
        # NOTE: `lock` is injected from VaultManager state — never accept it
        # from caller's kwargs. Refactors that change kwargs handling
        # MUST keep this self-injection.
        return writer_mod.trace_export(
            vault_root=self.vault_root,
            lock=self.lock,
            retention_hours=self.config.vault.traces.retention_hours,
            **kwargs,
        )

    def run_prune_cycle(self) -> dict:
        """One pass of the pruner: TTL prune + _stale/ refresh + fan-out."""
        if not self._started:
            return {}
        results = {}
        results["traces"] = pruner_mod.prune_traces(
            vault_root=self.vault_root,
            max_retention_hours_hard=self.config.vault.traces.max_retention_hours_hard,
            rollup_enabled=self.config.vault.traces.rollup_enabled,
            rollup_shard=self.config.vault.traces.rollup_shard,
        )
        results["stale"] = pruner_mod.refresh_stale_view(
            vault_root=self.vault_root,
            genome=self.genome,
            stale_threshold=self.config.vault.stale_threshold,
            party_id=self.config.vault.party_id,
        )
        results["fan_out"] = pruner_mod.migrate_fan_out_if_needed(
            vault_root=self.vault_root,
            state=self.state,
            fan_out_threshold=self.config.vault.fan_out_threshold,
        )
        return results

    def status(self) -> dict:
        if not self._started:
            return {"enabled": False, "reason": "not started"}
        top = self.state.read_top_level_state()
        file_counts = self._compute_file_counts()
        disk_bytes = self._compute_disk_bytes()
        return {
            "enabled": True,
            "vault_root": str(self.vault_root),
            "last_full_export_ts": top["last_full_export_ts"],
            "last_incremental_export_ts": top["last_incremental_export_ts"],
            "exported_gene_count": top["exported_gene_count"],
            "watcher_state": 0,  # TODO(v1.1): file-watcher state (not yet wired)
            "file_counts": file_counts,
            "disk_bytes": disk_bytes,
        }

    def _compute_file_counts(self) -> dict:
        counts = {}
        for sub in ("genes", "_traces", "_traces-pinned", "_inbox", "_stale"):
            d = self.vault_root / sub
            if d.exists():
                counts[sub] = sum(1 for p in d.rglob("*.md"))
            else:
                counts[sub] = 0
        # Emit per-folder gauge values for Prometheus visibility.
        try:
            gauge = vault_file_count_gauge()
            for folder, count in counts.items():
                gauge.set(count, {"folder": folder})
        except Exception:
            pass  # noop-safe — telemetry must not break vault.status()
        return counts

    def _compute_disk_bytes(self) -> int:
        total = 0
        for p in self.vault_root.rglob("*"):
            if p.is_file():
                try:
                    total += p.stat().st_size
                except OSError:
                    pass
        return total
